In [14]:
#import statements
import pandas as pd
import json

In [15]:
#Review.json  - Properties taken : user_id, business_id, stars, useful, funny, cool, text
reviewCols = ['user_id', 'business_id', 'stars', 'useful', 'funny', 'cool', 'text', 'date']
data = []

with open('D:\\CBS_MSc_Docs\\Courses\\Sem3\\AIML25\\Project\\Yelp-JSON\\Yelp JSON\\yelp_dataset\\yelp_academic_dataset_review.json', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        # Extract only the desired properties
        data.append({col: record.get(col) for col in reviewCols})

df_review = pd.DataFrame(data)

f.close()
data = []

In [ ]:
#df_review

In [16]:
#Read tip.json - Properties taken : user_id, business_id, text, date

tipCols = ['user_id', 'business_id', 'text', 'date']

with open('D:\\CBS_MSc_Docs\\Courses\\Sem3\\AIML25\\Project\\Yelp-JSON\\Yelp JSON\\yelp_dataset\\yelp_academic_dataset_tip.json', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        # Extract only the desired properties
        data.append({col: record.get(col) for col in tipCols})

df_tip = pd.DataFrame(data)

f.close()
data = []

In [ ]:
#df_tip

In [19]:
df_review = pd.concat([df_review, df_tip], axis=0, ignore_index=True)
df_review

,user_id,business_id,stars,useful,funny,cool,text,date
0,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0.0,0.0,0.0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5.0,1.0,0.0,1.0,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3.0,0.0,0.0,0.0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1.0,0.0,1.0,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4.0,1.0,0.0,1.0,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15
...,...,...,...,...,...,...,...,...
7899190,eYodOTF8pkqKPzHkcxZs-Q,3lHTewuKFt5IImbXJoFeDQ,NaN,NaN,NaN,NaN,Disappointed in one of your managers.,2021-09-11 19:18:57
7899191,1uxtQAuJ2T5Xwa_wp7kUnA,OaGf0Dp56ARhQwIDT90w_g,NaN,NaN,NaN,NaN,Great food and service.,2021-10-30 11:54:36
7899192,v48Spe6WEpqehsF2xQADpg,hYnMeAO77RGyTtIzUSKYzQ,NaN,NaN,NaN,NaN,Love their Cubans!!,2021-11-05 13:18:56
7899193,ckqKGM2hl7I9Chp5IpAhkw,s2eyoTuJrcP7I_XyjdhUHQ,NaN,NaN,NaN,NaN,Great pizza great price,2021-11-20 16:11:44
7899194,4tF1CWdMxvvwpUIgGsDygA,_cb1Vg1NIWry8UA0jyuXnQ,NaN,NaN,NaN,NaN,Food is good value but a bit hot!,2021-12-07 22:30:00

Business.json - Properties taken : business_id, name, stars, review_count, categories, 'attributes.ByAppointmentOnly', 'attributes.BusinessAcceptsCreditCards', 'attributes.BikeParking',
       'attributes.RestaurantsPriceRange2', 'attributes.CoatCheck',
       'attributes.RestaurantsTakeOut', 'attributes.RestaurantsDelivery',
       'attributes.Caters', 'attributes.WiFi', 'attributes.BusinessParking',
       'attributes.WheelchairAccessible', 'attributes.HappyHour',
       'attributes.OutdoorSeating', 'attributes.HasTV',
       'attributes.RestaurantsReservations', 'attributes.DogsAllowed', 'attributes.Alcohol', 'attributes.GoodForKids',
       'attributes.RestaurantsAttire', 'attributes.Ambience',
       'attributes.RestaurantsTableService',
       'attributes.RestaurantsGoodForGroups', 'attributes.DriveThru', 'attributes.NoiseLevel', 'attributes.GoodForMeal',
       'attributes.Smoking',
       'attributes.Music', 'attributes.GoodForDancing', 'attributes.BYOB', 'attributes.Corkage', 'attributes.BYOBCorkage'
       'attributes.Open24Hours',
       'attributes.RestaurantsCounterService', 'attributes.AgesAllowed',
       'attributes.DietaryRestrictions'

In [20]:
#Read Business.json

businessCols_drop = ['address', 'city', 'state', 'postal_code', 'latitude', 'longitude', 'is_open', 'hours','hours.Monday', 'hours.Tuesday', 'hours.Wednesday', 'hours.Thursday', 'hours.Friday', 'hours.Saturday', 'hours.Sunday', 'attributes.AcceptsInsurance', 'attributes.HairSpecializesIn']

with open('D:\\CBS_MSc_Docs\\Courses\\Sem3\\AIML25\\Project\\Yelp-JSON\\Yelp JSON\\yelp_dataset\\yelp_academic_dataset_business.json', encoding='utf-8') as f:
    for line in f:
        data.append(json.loads(line))

# Flatten the JSON
df_business = pd.json_normalize(data)

#Remove columns not required
df_business = df_business.drop(businessCols_drop, axis=1)

f.close()
data = []

#df_business.columns

In [21]:
#df_business

In [22]:
df_business2 = df_business[df_business["categories"].str.contains("Restaurants", na=False)]
df_business2

,business_id,name,stars,review_count,categories,attributes.ByAppointmentOnly,attributes.BusinessAcceptsCreditCards,attributes.BikeParking,attributes.RestaurantsPriceRange2,attributes.CoatCheck,...,attributes.Music,attributes.GoodForDancing,attributes.BestNights,attributes.BYOB,attributes.Corkage,attributes.BYOBCorkage,attributes.Open24Hours,attributes.RestaurantsCounterService,attributes.AgesAllowed,attributes.DietaryRestrictions
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,4.0,80,"Restaurants, Food, Bubble Tea, Coffee & Tea, B...",False,False,True,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,2.0,6,"Burgers, Fast Food, Sandwiches, Food, Ice Crea...",False,True,False,1,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,k0hlBqXX-Bt0vf1op7Jr1w,Tsevi's Pub And Grill,3.0,19,"Pubs, Restaurants, Italian, Bars, American (Tr...",NaN,True,NaN,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,1.5,10,"Ice Cream & Frozen Yogurt, Fast Food, Burgers,...",False,True,NaN,1,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,eEOYSgkmpB90uNA7lDOMRA,Vietnamese Food Truck,4.0,10,"Vietnamese, Food, Restaurants, Food Trucks",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150325,l9eLGG9ZKpLJzboZq-9LRQ,Wawa,3.0,11,"Restaurants, Sandwiches, Convenience Stores, C...",NaN,True,True,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150327,cM6V90ExQD6KMSU3rRB5ZA,Dutch Bros Coffee,4.0,33,"Cafes, Juice Bars & Smoothies, Coffee & Tea, R...",NaN,True,True,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150336,WnT9NIzQgLlILjPT0kEcsQ,Adelita Taqueria & Restaurant,4.5,35,"Restaurants, Mexican",NaN,True,True,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150339,2O2K6SXPWv56amqxCECd4w,The Plum Pit,4.5,14,"Restaurants, Comfort Food, Food, Food Trucks, ...",NaN,True,True,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150340,hn9Toz3s-Ei3uZPt7esExA,West Side Kebab House,4.5,18,"Middle Eastern, Restaurants",NaN,NaN,NaN,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
#Dataframe merge 
#Reviews X Business

dataset_df = pd.merge(df_review, df_business2, on="business_id")
dataset_df

,user_id,business_id,stars_x,useful,funny,cool,text,date,name,stars_y,...,attributes.Music,attributes.GoodForDancing,attributes.BestNights,attributes.BYOB,attributes.Corkage,attributes.BYOBCorkage,attributes.Open24Hours,attributes.RestaurantsCounterService,attributes.AgesAllowed,attributes.DietaryRestrictions
0,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0.0,0.0,0.0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11,Turning Point of North Wales,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3.0,0.0,0.0,0.0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30,Kettle Restaurant,3.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1.0,0.0,1.0,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03,Zaika,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4.0,1.0,0.0,1.0,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15,Melt,4.0,...,"{'dj': False, 'background_music': False, 'no_m...",False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,eUta8W_HdHMXPzLBBZhL1A,04UD14gamNjLY0IDYVhHJg,1.0,1.0,2.0,1.0,I am a long term frequent customer of this est...,2015-09-23 23:10:31,Dmitri's,4.0,...,NaN,NaN,NaN,NaN,NaN,'yes_free',NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5373616,FowxkbAixI3hlREeCgIa_Q,kfNv-JZpuN6TVNSO6hHdkw,NaN,NaN,NaN,NaN,Great experience with a phenomenal food with a...,2021-05-09 23:21:10,Hibachi Express,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5373617,1uxtQAuJ2T5Xwa_wp7kUnA,OaGf0Dp56ARhQwIDT90w_g,NaN,NaN,NaN,NaN,Great food and service.,2021-10-30 11:54:36,Sus Hi Eatstation,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5373618,v48Spe6WEpqehsF2xQADpg,hYnMeAO77RGyTtIzUSKYzQ,NaN,NaN,NaN,NaN,Love their Cubans!!,2021-11-05 13:18:56,The Strawberry Hut,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5373619,ckqKGM2hl7I9Chp5IpAhkw,s2eyoTuJrcP7I_XyjdhUHQ,NaN,NaN,NaN,NaN,Great pizza great price,2021-11-20 16:11:44,Bros Pizzeria,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5373620,4tF1CWdMxvvwpUIgGsDygA,_cb1Vg1NIWry8UA0jyuXnQ,NaN,NaN,NaN,NaN,Food is good value but a bit hot!,2021-12-07 22:30:00,Cheng Du,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
#checking if merged properly
df_check = dataset_df[dataset_df["name"] == "Zaika"]
df_check

,user_id,business_id,stars_x,useful,funny,cool,text,date,name,stars_y,...,attributes.Music,attributes.GoodForDancing,attributes.BestNights,attributes.BYOB,attributes.Corkage,attributes.BYOBCorkage,attributes.Open24Hours,attributes.RestaurantsCounterService,attributes.AgesAllowed,attributes.DietaryRestrictions
2,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1.0,0.0,1.0,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03,Zaika,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,kSMOJwJXuEUqzfmuFncK4A,kxX2SOes4o-D3ZQBkiMRfA,2.0,0.0,0.0,1.0,Dine-in gets 2 stars. Disappointing service & ...,2014-07-13 17:25:47,Zaika,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
371,mqBWACmaHflW4eh_Ofp16Q,kxX2SOes4o-D3ZQBkiMRfA,5.0,13.0,6.0,5.0,After a long hiatus from reviewing I have awak...,2010-08-20 19:16:04,Zaika,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3365,Z-xgVb4nM42943m2wbBkFw,kxX2SOes4o-D3ZQBkiMRfA,5.0,1.0,1.0,1.0,We've eaten here 3 times and it seems that eac...,2017-01-02 14:25:26,Zaika,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5349,2SEoXb6r6hPKrl9V9VzBgA,kxX2SOes4o-D3ZQBkiMRfA,5.0,0.0,0.0,0.0,Came to Philly for a family event but stayed a...,2015-07-28 17:15:20,Zaika,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5176721,RAVr_68v9aXWs9haVSYcGg,kxX2SOes4o-D3ZQBkiMRfA,NaN,NaN,NaN,NaN,Closed on Mondays!,2012-07-24 02:16:49,Zaika,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5262989,Im6KghACvPySx8Li962BDQ,kxX2SOes4o-D3ZQBkiMRfA,NaN,NaN,NaN,NaN,Food was great and service was even better!,2017-09-03 04:35:42,Zaika,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5296835,4t1i2zOdRvSah2DJTTzIvw,kxX2SOes4o-D3ZQBkiMRfA,NaN,NaN,NaN,NaN,Awsm food. Awsm price. Loved the mutton biryani.,2014-12-15 22:28:46,Zaika,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5312954,AUCWNlO7naqufPCt3vOIaA,kxX2SOes4o-D3ZQBkiMRfA,NaN,NaN,NaN,NaN,Great food! Especially seeing what options are...,2020-01-21 18:48:29,Zaika,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5320493,vA5KdTavd3hshACQPj2R7Q,kxX2SOes4o-D3ZQBkiMRfA,NaN,NaN,NaN,NaN,"Taste of food-wise, this place is top notch. I...",2012-06-21 00:33:39,Zaika,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
dataset_df.rename(columns={'stars_x': 'stars_user', 'stars_y': 'stars_overall'}, inplace=True)
dataset_df

,user_id,business_id,stars_user,useful,funny,cool,text,date,name,stars_overall,...,attributes.Music,attributes.GoodForDancing,attributes.BestNights,attributes.BYOB,attributes.Corkage,attributes.BYOBCorkage,attributes.Open24Hours,attributes.RestaurantsCounterService,attributes.AgesAllowed,attributes.DietaryRestrictions
0,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0.0,0.0,0.0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11,Turning Point of North Wales,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3.0,0.0,0.0,0.0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30,Kettle Restaurant,3.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1.0,0.0,1.0,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03,Zaika,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4.0,1.0,0.0,1.0,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15,Melt,4.0,...,"{'dj': False, 'background_music': False, 'no_m...",False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,eUta8W_HdHMXPzLBBZhL1A,04UD14gamNjLY0IDYVhHJg,1.0,1.0,2.0,1.0,I am a long term frequent customer of this est...,2015-09-23 23:10:31,Dmitri's,4.0,...,NaN,NaN,NaN,NaN,NaN,'yes_free',NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5373616,FowxkbAixI3hlREeCgIa_Q,kfNv-JZpuN6TVNSO6hHdkw,NaN,NaN,NaN,NaN,Great experience with a phenomenal food with a...,2021-05-09 23:21:10,Hibachi Express,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5373617,1uxtQAuJ2T5Xwa_wp7kUnA,OaGf0Dp56ARhQwIDT90w_g,NaN,NaN,NaN,NaN,Great food and service.,2021-10-30 11:54:36,Sus Hi Eatstation,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5373618,v48Spe6WEpqehsF2xQADpg,hYnMeAO77RGyTtIzUSKYzQ,NaN,NaN,NaN,NaN,Love their Cubans!!,2021-11-05 13:18:56,The Strawberry Hut,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5373619,ckqKGM2hl7I9Chp5IpAhkw,s2eyoTuJrcP7I_XyjdhUHQ,NaN,NaN,NaN,NaN,Great pizza great price,2021-11-20 16:11:44,Bros Pizzeria,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5373620,4tF1CWdMxvvwpUIgGsDygA,_cb1Vg1NIWry8UA0jyuXnQ,NaN,NaN,NaN,NaN,Food is good value but a bit hot!,2021-12-07 22:30:00,Cheng Du,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN