In [1]:
#import statements
import pandas as pd
import json
data = []

In [2]:
#Review.json  - Properties taken : user_id, business_id, stars, useful, funny, cool, text
reviewCols = ['user_id', 'business_id', 'stars', 'useful', 'funny', 'cool', 'text', 'date']

with open('/Users/saad.ifty/Desktop/CBS/3rd Semester/AIML25/AIML_project/data/Yelp JSON/yelp_dataset/yelp_academic_dataset_review.json', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        # Extract only the desired properties
        data.append({col: record.get(col) for col in reviewCols})

df_review = pd.DataFrame(data)

f.close()
data = []

In [3]:
#df_review

In [4]:
#Read tip.json - Properties taken : user_id, business_id, text, date

#Discarding this as one user can post multiple tips for a business and we found fake/dirty data

'''tipCols = ['user_id', 'business_id', 'text', 'date']

with open('data/yelp_academic_dataset_tip.json', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        # Extract only the desired properties
        data.append({col: record.get(col) for col in tipCols})

df_tip = pd.DataFrame(data)

f.close()
data = []'''

'''df_review = pd.concat([df_review, df_tip], axis=0, ignore_index=True)
df_review'''

'df_review = pd.concat([df_review, df_tip], axis=0, ignore_index=True)\ndf_review'

Index(['business_id', 'name', 'review_count', 'categories',
       'attributes.ByAppointmentOnly', 'attributes.BusinessAcceptsCreditCards',
       'attributes.BikeParking', 'attributes.RestaurantsPriceRange2',
       'attributes.CoatCheck', 'attributes.RestaurantsTakeOut',
       'attributes.RestaurantsDelivery', 'attributes.Caters',
       'attributes.WiFi', 'attributes.BusinessParking',
       'attributes.WheelchairAccessible', 'attributes.HappyHour',
       'attributes.OutdoorSeating', 'attributes.HasTV',
       'attributes.RestaurantsReservations', 'attributes.DogsAllowed',
       'attributes.Alcohol', 'attributes.GoodForKids',
       'attributes.RestaurantsAttire', 'attributes.Ambience',
       'attributes.RestaurantsTableService',
       'attributes.RestaurantsGoodForGroups', 'attributes.DriveThru',
       'attributes', 'attributes.NoiseLevel', 'attributes.GoodForMeal',
       'attributes.BusinessAcceptsBitcoin', 'attributes.Smoking',
       'attributes.Music', 'attributes.GoodForDancing',
       'attributes.BestNights', 'attributes.BYOB', 'attributes.Corkage',
       'attributes.BYOBCorkage', 'attributes.Open24Hours',
       'attributes.RestaurantsCounterService', 'attributes.AgesAllowed',
       'attributes.DietaryRestrictions'],
      dtype='object')

In [5]:
#Read Business.json

businessCols = ['business_id','name','review_count','categories','address', 'city', 'state', 'postal_code']

with open('/Users/saad.ifty/Desktop/CBS/3rd Semester/AIML25/AIML_project/data/Yelp JSON/yelp_dataset/yelp_academic_dataset_business.json', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        # Extract only the desired properties
        data.append({col: record.get(col) for col in businessCols})

# Flatten the JSON
#df_business = pd.json_normalize(data)

#Remove columns not required
df_business = pd.DataFrame(data)

f.close()
data = []

#df_business.columns

In [6]:
#df_business

In [7]:
#keep businesses which contains 'Restaurants and Food' as part of category
df_business2 = df_business[df_business["categories"].str.contains("Restaurants|Food", na=False)]
df_business2

,business_id,name,review_count,categories,address,city,state,postal_code
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,80,"Restaurants, Food, Bubble Tea, Coffee & Tea, B...",935 Race St,Philadelphia,PA,19107
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,13,"Brewpubs, Breweries, Food",101 Walnut St,Green Lane,PA,18054
5,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,6,"Burgers, Fast Food, Sandwiches, Food, Ice Crea...",615 S Main St,Ashland City,TN,37015
8,k0hlBqXX-Bt0vf1op7Jr1w,Tsevi's Pub And Grill,19,"Pubs, Restaurants, Italian, Bars, American (Tr...",8025 Mackenzie Rd,Affton,MO,63123
9,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,10,"Ice Cream & Frozen Yogurt, Fast Food, Burgers,...",2312 Dickerson Pike,Nashville,TN,37207
...,...,...,...,...,...,...,...,...
150327,cM6V90ExQD6KMSU3rRB5ZA,Dutch Bros Coffee,33,"Cafes, Juice Bars & Smoothies, Coffee & Tea, R...",1181 N Milwaukee St,Boise,ID,83704
150328,1jx1sfgjgVg0nM6n3p0xWA,Savaya Coffee Market,41,"Specialty Food, Food, Coffee & Tea, Coffee Roa...",11177 N Oracle Rd,Oro Valley,AZ,85737
150336,WnT9NIzQgLlILjPT0kEcsQ,Adelita Taqueria & Restaurant,35,"Restaurants, Mexican",1108 S 9th St,Philadelphia,PA,19147
150339,2O2K6SXPWv56amqxCECd4w,The Plum Pit,14,"Restaurants, Comfort Food, Food, Food Trucks, ...",4405 Pennell Rd,Aston,DE,19014
150340,hn9Toz3s-Ei3uZPt7esExA,West Side Kebab House,18,"Middle Eastern, Restaurants",2470 Guardian Road NW,Edmonton,AB,T5T 1K8

In [8]:
#count number of restaurants with same name 
v = df_business2["name"].value_counts()
v

name
Starbucks                      724
McDonald's                     703
Dunkin'                        510
Subway                         459
Taco Bell                      365
                              ...
Alma Mater                       1
Varalli                          1
Rosies Deli & Sandwich Shop      1
Jin China                        1
West Side Kebab House            1
Name: count, Length: 43836, dtype: int64

In [9]:
#filter restaurants which have more than 6 branches
df_business2 = df_business2[df_business2["name"].isin(v.index[v.gt(6)])]
df_business2

,business_id,name,review_count,categories,address,city,state,postal_code
5,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,6,"Burgers, Fast Food, Sandwiches, Food, Ice Crea...",615 S Main St,Ashland City,TN,37015
9,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,10,"Ice Cream & Frozen Yogurt, Fast Food, Burgers,...",2312 Dickerson Pike,Nashville,TN,37207
12,il_Ro8jwPlHresjw9EGmBg,Denny's,28,"American (Traditional), Restaurants, Diners, B...",8901 US 31 S,Indianapolis,IN,46227
22,kfNv-JZpuN6TVNSO6hHdkw,Hibachi Express,20,"Steakhouses, Asian Fusion, Restaurants",6625 E 82nd St,Indianapolis,IN,46250
23,9OG5YkX1g2GReZM0AskizA,Romano's Macaroni Grill,339,"Restaurants, Italian",5505 S Virginia St,Reno,NV,89502
...,...,...,...,...,...,...,...,...
150313,sf_oQ62L8UEnOOLf00nNGA,Pizza Hut,6,"Restaurants, Pizza, Fast Food, Chicken Wings, ...",5028 Old Hickory,Hermitage,TN,37076
150315,WXNag-tmudrFHFlfNLogWg,Whole Foods Market,71,"Health Markets, Specialty Food, Food, Grocery",4577 W Pine Blvd,St. Louis,MO,63108
150321,AM7O0cwkxm6w_e0Q7-f9FQ,Starbucks,29,"Food, Coffee & Tea",8817 S US-31,Indianapolis,IN,46227
150325,l9eLGG9ZKpLJzboZq-9LRQ,Wawa,11,"Restaurants, Sandwiches, Convenience Stores, C...",19 N Bishop Ave,Clifton Heights,PA,19018
150327,cM6V90ExQD6KMSU3rRB5ZA,Dutch Bros Coffee,33,"Cafes, Juice Bars & Smoothies, Coffee & Tea, R...",1181 N Milwaukee St,Boise,ID,83704

In [10]:
#verify it does what we need --business2
df_business3 = df_business2[df_business2["name"].str.contains("Taco Bell", na=False)]
df_business3

,business_id,name,review_count,categories,address,city,state,postal_code
1067,H2nFgEFitRk7ltE8IRH0xA,Taco Bell,42,"Restaurants, Tex-Mex, Breakfast & Brunch, Mexi...",4647 West Kennedy Blvd,Tampa,FL,33609
1191,i8UZblHPk2O-iNKJrnWQ_Q,Taco Bell,26,"Restaurants, Fast Food, Mexican, Tex-Mex, Taco...",8578 East Broadway Blvd,Tucson,AZ,85710
2150,YWcH3SLyRIBHIBBgudqZLw,Taco Bell,8,"Fast Food, Restaurants, Breakfast & Brunch, Ve...",1616 Camp Jackson Road,Cahokia,IL,62206
3007,c6xp1swmd-_P87kt3xggDA,Taco Bell,16,"Restaurants, Fast Food, Tex-Mex, Tacos, Mexican",620 E. Landmarks Blvd.,Alton,IL,62002
3321,X8k7N03buo2bBbUUfcAltQ,Taco Bell,38,"Restaurants, Fast Food, Breakfast & Brunch, Me...",645 S Main St,Meridian,ID,83642
...,...,...,...,...,...,...,...,...
149074,SMcCozP4wjNJ8hs7ZW5tnw,Taco Bell,25,"Restaurants, Tex-Mex, Breakfast & Brunch, Mexi...",11007 North Dale Mabry,Tampa,FL,33618
149175,y-B-ukhP-i4D6ZGwTl2jRg,Taco Bell,21,"Tex-Mex, Restaurants, Breakfast & Brunch, Fast...",3803 West Minnehaha Street,Tampa,FL,33614
149963,iNKg6firpzD5u5O1Gqd0HA,Taco Bell,20,"Fast Food, Breakfast & Brunch, Restaurants, Ta...",12420 St Charles Rock Rd,Bridgeton,MO,63044
150087,hezQG50YXqdgxkhl2R9OuQ,Taco Bell,30,"Fast Food, Restaurants, Breakfast & Brunch, Ta...",7620 West Hillsborough Avenue,Tampa,FL,33615
150166,BzPTw9daJW8ToqTc7QiHFw,Taco Bell,7,"Restaurants, Tex-Mex, Fast Food, Mexican, Taco...",590 S Broad Street,Trenton,NJ,08611

In [11]:
#Dataframe merge ---- Main Dataset!!!
#Reviews X Business2df

dataset_df = pd.merge(df_review, df_business2, on="business_id")
dataset_df

,user_id,business_id,stars,useful,funny,cool,text,date,name,review_count,categories,address,city,state,postal_code
0,QzCEzH3R7Z6erOGLr3t55Q,0pMj5xUAecW9o1P35B0AMw,5.0,1,0,1,Great staff always helps and always nice. Alwa...,2017-05-26 13:10:24,Wawa,8,"Food, Coffee & Tea, Gas Stations, Restaurants,...",2544 W Main Street,Norristown,PA,19403
1,3MpDvy5gEdsbZh9-p92dHg,8QnuWGVNBhzyYXGSeRdi4g,4.0,0,0,0,After my ROTD yesterday of a different Sweet ...,2013-10-24 19:24:33,Sweet Cece's,17,"Food, Ice Cream & Frozen Yogurt",7114 Hwy 70 S,Nashville,TN,37221
2,bCla27ma_6i_QFrGkILKrQ,sLgnx_WFCjEoPsS6NwU70Q,5.0,0,0,0,Our family returned for breakfast again this w...,2014-10-27 16:31:37,Le Peep,259,"Event Planning & Services, Salad, Caterers, Am...",3036 N Eagle Rd,Meridian,ID,83646
3,UsBxLh14sUpO8SdeqIiGOA,Wy8Hswf2cLQGRZN6armkag,1.0,1,0,0,"If I could give it a zero, I would. I order a ...",2011-08-24 23:07:08,Jack in the Box,86,"Restaurants, Fast Food, Mexican, Tacos, Burger...",6875 Hollister Ave,Goleta,CA,93117
4,mEOMAeEonZoUx2nPM3v6fg,f-WhNOSwN1aB4nRFekf01g,4.0,0,0,0,Id you haven't been to the Smoothie King cente...,2015-03-19 00:30:09,Smoothie King,50,"Arts & Entertainment, Ticket Sales, Food, Juic...",1501 Dave Dixon Drive Space 101-102,New Orleans,LA,70113
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586709,6YRmtPVvnD_mexQifxAJsg,IkjBNJvMZhea1c3j2H2Ahw,3.0,0,0,0,"Besides it being super busy often, usually, I ...",2022-01-10 12:51:07,Starbucks,31,"Food, Coffee & Tea",2350 South Grand Ave,St. Louis,MO,63104
586710,6Hmh8UC5K0oBgp3_D5doDQ,BxveKq0rKp52EWooIDK54w,2.0,3,1,0,Where do i begin. Overall the food was fine. I...,2019-12-08 19:24:12,Denny's,88,"Breakfast & Brunch, American (Traditional), Re...",3155 E Fairview Ave,Meridian,ID,83642
586711,UfevNSM_H14XXWZFlHYPoA,TNtcjnta11CpDebuBNdoug,2.0,0,1,0,Our waiter was good but a bit rushed. I didn't...,2017-10-22 20:55:12,Red Robin Gourmet Burgers and Brews,83,"Home Services, American (New), Contractors, Am...",130 Gravois Bluffs Cir,Fenton,MO,63026
586712,LHWtjTG7e1NzNPYUbUo-9w,rgeuy1qbw6Z8B6CSVANHIA,5.0,1,1,1,I've been to the other Federal Donuts location...,2012-10-13 14:39:37,Federal Donuts,1464,"Donuts, Sandwiches, Soul Food, Food, Coffee & ...",1632 Sansom St,Philadelphia,PA,19103
586713,x1QLCwZGFAjxRRw4EHc3-g,1_BVWDzi5cVqWxNe9bOMMQ,5.0,1,0,1,Don't misinterpret my 5-star review....I don't...,2016-04-30 01:02:34,Wendy's,55,"Restaurants, Burgers, Food, Fast Food",2130 Hampton Avenue,St.Louis,MO,63139

In [12]:
#checking if merged properly
#df_check = dataset_df[dataset_df["business_id"].isna()]
#df_check
dataset_df["text"].isnull().values.any()

False

In [13]:
duplicates = dataset_df[dataset_df.duplicated(subset=['user_id'], keep=False)]
#print(duplicates)

#mqBWACmaHflW4eh_Ofp16Q
duplicates = duplicates[duplicates["user_id"].str.contains("J7R2lsHoRAVIHXhcrSTlGQ")]
print(duplicates[["user_id", "text"]])

Empty DataFrame
Columns: [user_id, text]
Index: []

In [14]:
#Check if there are multiple entries from same user for same business
users = []
users = dataset_df[["user_id", "business_id"]].value_counts()
users

user_id                 business_id
EryvaUTsMnk26eiauFWapQ  3_icitB518vI8Hr0wEzl8A    29
I6x-ZBHeCNlMnmtfUVf5lg  cuXUuoOSZ4VbV6jvh3BC0A    22
xWmYN57XXZbg0LOK8WbbFQ  yzcZ0VkgyxmiH5M_87ADOg    14
tvmJO7-aCNssNcGIAsPYFA  SZNnDfhSryMHfZCfifHl7w    14
EryvaUTsMnk26eiauFWapQ  3Sb8JA3-URa4ElbRjAhkgQ    13
                                                  ..
Keiy6BmoThEnfmXPNX5hYw  i4Fbd8a3P2xLbK2lFo2HEg     1
KeiRIYyS549Wnk9n0rkjrQ  MIvgwMnwBYMygT8Fq4--ag     1
KeiM7LP-zPY6OLP6U7LO2g  ukQv_5rrCEx5NY7ZBZy1kQ     1
KeiEvgsR90tH1QOCklp2Tg  XB6FBOSetUsSb-b9-9Shrw     1
zzzCg-_lpyYE82TlJCdwdw  LttC5xNMFcgOg3bt_MlXTg     1
Name: count, Length: 563021, dtype: int64

In [16]:
#Check if there are multiple entries from same user for same business

multiple_reviews = dataset_df.loc[(dataset_df["user_id"] == "EryvaUTsMnk26eiauFWapQ") & (dataset_df["business_id"] == "3_icitB518vI8Hr0wEzl8A"), :]
multiple_reviews

,user_id,business_id,stars,useful,funny,cool,text,date,name,review_count,categories,address,city,state,postal_code
155840,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,5.0,1,0,1,"There is a Lovely, young gal named Marissa who...",2020-03-24 20:33:39,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
160504,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,5.0,2,0,1,Just had the best experience EVER at Wally. An...,2020-03-09 00:16:58,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
162970,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,1.0,0,0,0,My hubby took me to the jewelry counter today....,2021-12-18 02:14:09,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
163675,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,5.0,2,0,2,Was waited on by Minda today. Such a professio...,2021-08-28 22:15:57,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
163676,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,5.0,1,0,2,Recieved Excellent Service today in Sporting G...,2021-04-01 01:22:06,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
166133,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,5.0,1,0,1,Although I have not always gotten along with N...,2019-03-19 21:16:05,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
166389,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,5.0,1,0,2,Literally went to Wally for a bottle of Drano....,2021-07-22 02:29:22,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
166749,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,5.0,1,0,1,I usually go through Self Checkout. I am a Che...,2020-10-04 22:30:25,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
167307,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,5.0,0,0,0,We just finished using self checkout with the ...,2020-08-28 19:05:03,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
167409,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,5.0,1,0,1,"Just left wally with a Beautiful, Brand New Mi...",2019-05-07 19:54:38,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
167520,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,5.0,2,0,2,Met a Delightful Young man named Jose in the P...,2021-05-24 02:36:01,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
167985,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,1.0,1,0,0,The new male CSM is a Horror Show. Totally and...,2021-04-19 03:42:04,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
168942,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,1.0,0,0,0,I had a checker refuse to go check the price o...,2021-04-16 01:24:16,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
169415,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,5.0,2,1,2,It's Thanksgiving. I was trying to send my Fam...,2019-11-28 17:21:26,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
170658,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,5.0,3,0,2,Was feeling low and depressed. Had a bad exper...,2019-01-20 21:07:16,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
171229,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,5.0,0,0,0,Today was So Happy to be waited on by Robert a...,2021-08-02 23:32:24,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
171253,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,2.0,1,0,0,Bought a Brand New 30 dollar fan about 2 month...,2019-08-14 02:13:27,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
171568,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,4.0,2,0,2,"Went through Sheila's line. She is friendly, F...",2021-07-03 14:08:42,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
171770,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,5.0,2,0,1,Just used the pickup curbside service for the ...,2020-10-28 21:06:41,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
172318,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,4.0,1,0,1,I was trying to get my husband a decent flip p...,2017-11-12 22:02:48,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
172591,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,5.0,1,0,1,We were waited on by Hector today. What a Dyna...,2021-09-10 22:53:33,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
172898,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,2.0,0,0,0,For only the second time I have returned a bad...,2018-12-15 17:40:00,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
172963,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,5.0,0,0,0,Today is Jan. 21st. At approximately 4 PM a De...,2021-01-22 01:01:16,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
173360,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,2.0,1,0,0,This is my Wal-Mart. My neighborhood store. I ...,2021-06-22 20:24:34,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
173504,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,5.0,2,0,1,"My girlfriend, Verenice and I met the most Del...",2021-08-01 02:29:00,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
173649,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,5.0,1,0,1,Met the Spectacular Armando today. He is Aweso...,2021-08-11 17:38:23,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
173676,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,5.0,0,0,0,Was at my favorite Wally Super Store and had s...,2021-05-27 20:43:50,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
173728,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,3.0,0,0,0,I give 3 stars today. I just went there and re...,2020-04-07 19:37:16,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502
173996,EryvaUTsMnk26eiauFWapQ,3_icitB518vI8Hr0wEzl8A,5.0,1,0,1,Walmart now offers self checkout. It would be ...,2017-10-22 23:04:44,Walmart Supercenter,158,"Department Stores, Shopping, Grocery, Discount...",2425 E 2nd St,Reno,NV,89502

In [17]:
#imports for text preprocessing

import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

from nltk.corpus import stopwords
from nltk.tokenize import TreebankWordTokenizer
from nltk.stem import WordNetLemmatizer
import string

tokenizer = TreebankWordTokenizer()
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package punkt to /Users/saad.ifty/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/saad.ifty/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/saad.ifty/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/saad.ifty/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [18]:
#Defining a text cleaning function

def preprocess_text(text):
    # 1. Lowercase
    text = text.lower()

    # 2. Tokenize
    tokens = tokenizer.tokenize(text)

    # 3. Remove punctuation and stopwords
    tokens = [word for word in tokens if word not in stop_words and word not in string.punctuation]

    # 4. Lemmatize
    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    # Return cleaned text
    return " ".join(tokens)

In [19]:
#Applying to our dataset

dataset_df['cleaned_text'] = dataset_df['text'].apply(preprocess_text)

In [20]:
print(dataset_df[['text', 'cleaned_text']].head(5))

                                                text  \
0  Great staff always helps and always nice. Alwa...
1  After my ROTD  yesterday of a different Sweet ...
2  Our family returned for breakfast again this w...
3  If I could give it a zero, I would. I order a ...
4  Id you haven't been to the Smoothie King cente...

                                        cleaned_text
0  great staff always help always nice. always cl...
1  rotd yesterday different sweet cece 's locatio...
2  family returned breakfast weekend food service...
3  could give zero would. order plain hamburger r...
4  id n't smoothie king center since know new orl...

Suggestions by Nicolai:

Design choice - do A to C first then the other model

Explain why you chose the model - why and how did you apply this to the business Model

Try using smaller language model 7 million - one - reason - run through more data - more money

Try to use - instructor / response models - consistent and structuired op from llm

future examples and chain of thought

How to train - models that do sentiment already - HuggingFace - roberta - base models

use models like roberta to label it - ideal world you do human and AI annotation

Everywhere where confidence is over 85 - we assume it to be true if less we take a look at the sentiment and correct it.

ensemble models (LAST!!!!) - multiple models running at the same time - more agree more certain - 4 or more models running at the same time