In [12]:
#import statements
import pandas as pd
import json
data = []

In [40]:
#Review.json  - Properties taken : user_id, business_id, stars, useful, funny, cool, text
reviewCols = ['user_id', 'business_id', 'stars', 'useful', 'funny', 'cool', 'text', 'date']

with open('D:\\CBS_MSc_Docs\\Courses\\Sem3\\AIML\\Project\\Yelp-JSON\\Yelp JSON\\yelp_dataset\\yelp_academic_dataset_review.json', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        # Extract only the desired properties
        data.append({col: record.get(col) for col in reviewCols})

df_review = pd.DataFrame(data)

f.close()
data = []

In [ ]:
#df_review

In [41]:
#Read tip.json - Properties taken : user_id, business_id, text, date

tipCols = ['user_id', 'business_id', 'text', 'date']

with open('D:\\CBS_MSc_Docs\\Courses\\Sem3\\AIML\\Project\\Yelp-JSON\\Yelp JSON\\yelp_dataset\\yelp_academic_dataset_tip.json', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        # Extract only the desired properties
        data.append({col: record.get(col) for col in tipCols})

df_tip = pd.DataFrame(data)

f.close()
data = []

In [ ]:
#df_tip

In [42]:
df_review = pd.concat([df_review, df_tip], axis=0, ignore_index=True)
df_review

,user_id,business_id,stars,useful,funny,cool,text,date
0,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0.0,0.0,0.0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5.0,1.0,0.0,1.0,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3.0,0.0,0.0,0.0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1.0,0.0,1.0,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4.0,1.0,0.0,1.0,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15
...,...,...,...,...,...,...,...,...
7899190,eYodOTF8pkqKPzHkcxZs-Q,3lHTewuKFt5IImbXJoFeDQ,NaN,NaN,NaN,NaN,Disappointed in one of your managers.,2021-09-11 19:18:57
7899191,1uxtQAuJ2T5Xwa_wp7kUnA,OaGf0Dp56ARhQwIDT90w_g,NaN,NaN,NaN,NaN,Great food and service.,2021-10-30 11:54:36
7899192,v48Spe6WEpqehsF2xQADpg,hYnMeAO77RGyTtIzUSKYzQ,NaN,NaN,NaN,NaN,Love their Cubans!!,2021-11-05 13:18:56
7899193,ckqKGM2hl7I9Chp5IpAhkw,s2eyoTuJrcP7I_XyjdhUHQ,NaN,NaN,NaN,NaN,Great pizza great price,2021-11-20 16:11:44
7899194,4tF1CWdMxvvwpUIgGsDygA,_cb1Vg1NIWry8UA0jyuXnQ,NaN,NaN,NaN,NaN,Food is good value but a bit hot!,2021-12-07 22:30:00

Index(['business_id', 'name', 'review_count', 'categories',
       'attributes.ByAppointmentOnly', 'attributes.BusinessAcceptsCreditCards',
       'attributes.BikeParking', 'attributes.RestaurantsPriceRange2',
       'attributes.CoatCheck', 'attributes.RestaurantsTakeOut',
       'attributes.RestaurantsDelivery', 'attributes.Caters',
       'attributes.WiFi', 'attributes.BusinessParking',
       'attributes.WheelchairAccessible', 'attributes.HappyHour',
       'attributes.OutdoorSeating', 'attributes.HasTV',
       'attributes.RestaurantsReservations', 'attributes.DogsAllowed',
       'attributes.Alcohol', 'attributes.GoodForKids',
       'attributes.RestaurantsAttire', 'attributes.Ambience',
       'attributes.RestaurantsTableService',
       'attributes.RestaurantsGoodForGroups', 'attributes.DriveThru',
       'attributes', 'attributes.NoiseLevel', 'attributes.GoodForMeal',
       'attributes.BusinessAcceptsBitcoin', 'attributes.Smoking',
       'attributes.Music', 'attributes.GoodForDancing',
       'attributes.BestNights', 'attributes.BYOB', 'attributes.Corkage',
       'attributes.BYOBCorkage', 'attributes.Open24Hours',
       'attributes.RestaurantsCounterService', 'attributes.AgesAllowed',
       'attributes.DietaryRestrictions'],
      dtype='object')

In [22]:
#Read Business.json

businessCols = ['business_id','name','review_count','categories','address', 'city', 'state', 'postal_code']

with open('D:\\CBS_MSc_Docs\\Courses\\Sem3\\AIML\\Project\\Yelp-JSON\\Yelp JSON\\yelp_dataset\\yelp_academic_dataset_business.json', encoding='utf-8') as f:
    for line in f:
        record = json.loads(line)
        # Extract only the desired properties
        data.append({col: record.get(col) for col in businessCols})

# Flatten the JSON
#df_business = pd.json_normalize(data)

#Remove columns not required
df_business = pd.DataFrame(data)

f.close()
data = []

#df_business.columns

In [23]:
df_business

,business_id,name,review_count,categories,address,city,state,postal_code
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ",7,"Doctors, Traditional Chinese Medicine, Naturop...","1616 Chapala St, Ste 2",Santa Barbara,CA,93101
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,15,"Shipping Centers, Local Services, Notaries, Ma...",87 Grasso Plaza Shopping Center,Affton,MO,63123
2,tUFrWirKiKi_TAnsVWINQQ,Target,22,"Department Stores, Shopping, Fashion, Home & G...",5255 E Broadway Blvd,Tucson,AZ,85711
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,80,"Restaurants, Food, Bubble Tea, Coffee & Tea, B...",935 Race St,Philadelphia,PA,19107
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,13,"Brewpubs, Breweries, Food",101 Walnut St,Green Lane,PA,18054
...,...,...,...,...,...,...,...,...
150341,IUQopTMmYQG-qRtBk-8QnA,Binh's Nails,13,"Nail Salons, Beauty & Spas",3388 Gateway Blvd,Edmonton,AB,T6J 5H2
150342,c8GjPIOTGVmIemT7j5_SyQ,Wild Birds Unlimited,5,"Pets, Nurseries & Gardening, Pet Stores, Hobby...",2813 Bransford Ave,Nashville,TN,37204
150343,_QAMST-NrQobXduilWEqSw,Claire's Boutique,8,"Shopping, Jewelry, Piercing, Toy Stores, Beaut...","6020 E 82nd St, Ste 46",Indianapolis,IN,46250
150344,mtGm22y5c2UHNXDFAjaPNw,Cyclery & Fitness Center,24,"Fitness/Exercise Equipment, Eyewear & Optician...",2472 Troy Rd,Edwardsville,IL,62025
150345,jV_XOycEzSlTx-65W906pg,Sic Ink,9,"Beauty & Spas, Permanent Makeup, Piercing, Tattoo",238 Apollo Beach Blvd,Apollo beach,FL,33572

In [36]:
#keep businesses which contains 'Restaurants' as part of category
df_business2 = df_business[df_business["categories"].str.contains("Restaurants|Food", na=False)]
df_business2

,business_id,name,review_count,categories,address,city,state,postal_code
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,80,"Restaurants, Food, Bubble Tea, Coffee & Tea, B...",935 Race St,Philadelphia,PA,19107
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,13,"Brewpubs, Breweries, Food",101 Walnut St,Green Lane,PA,18054
5,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,6,"Burgers, Fast Food, Sandwiches, Food, Ice Crea...",615 S Main St,Ashland City,TN,37015
8,k0hlBqXX-Bt0vf1op7Jr1w,Tsevi's Pub And Grill,19,"Pubs, Restaurants, Italian, Bars, American (Tr...",8025 Mackenzie Rd,Affton,MO,63123
9,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,10,"Ice Cream & Frozen Yogurt, Fast Food, Burgers,...",2312 Dickerson Pike,Nashville,TN,37207
...,...,...,...,...,...,...,...,...
150327,cM6V90ExQD6KMSU3rRB5ZA,Dutch Bros Coffee,33,"Cafes, Juice Bars & Smoothies, Coffee & Tea, R...",1181 N Milwaukee St,Boise,ID,83704
150328,1jx1sfgjgVg0nM6n3p0xWA,Savaya Coffee Market,41,"Specialty Food, Food, Coffee & Tea, Coffee Roa...",11177 N Oracle Rd,Oro Valley,AZ,85737
150336,WnT9NIzQgLlILjPT0kEcsQ,Adelita Taqueria & Restaurant,35,"Restaurants, Mexican",1108 S 9th St,Philadelphia,PA,19147
150339,2O2K6SXPWv56amqxCECd4w,The Plum Pit,14,"Restaurants, Comfort Food, Food, Food Trucks, ...",4405 Pennell Rd,Aston,DE,19014
150340,hn9Toz3s-Ei3uZPt7esExA,West Side Kebab House,18,"Middle Eastern, Restaurants",2470 Guardian Road NW,Edmonton,AB,T5T 1K8

In [ ]:
#keep restaurants with reviews more than 100
#df_business2 = df_business2[df_business2["review_count"] >= 50]

#filter out chain restaurants only

In [38]:
df_business3 = df_business2[df_business2["name"].str.contains("Sonic Drive-In", na=False)]
df_business3

,business_id,name,review_count,categories,address,city,state,postal_code
49541,_jNK0N8pvwTlDJwy7WR7zw,Sonic Drive-In,110,"Ice Cream & Frozen Yogurt, Burgers, Fast Food,...",1220 Mc Carran Blvd,Reno,NV,89512
76074,5tZJaEsvEDowvbAtL8Jfig,Sonic Drive-In,76,"Burgers, Fast Food, American (Traditional), Fo...",3156 S Kingshighway Blvd,Saint Louis,MO,63139
97583,twAaV18KPw1vB7NqiOVbEw,Sonic Drive-In,97,"Burgers, Ice Cream & Frozen Yogurt, Fast Food,...",4995 Galleria Pkwy,Sparks,NV,89436
114809,FdLNzJYoe7U05uQSbK4zsA,Sonic Drive-In,58,"Ice Cream & Frozen Yogurt, Fast Food, Restaura...",2523 North Dale Mabry Hwy,Tampa,FL,33607
119486,7H1b6TZ-LNxyGx1cv9suJQ,Sonic Drive-In,64,"Food, Burgers, Fast Food, Restaurants, Dessert...",3913 Veterans Memorial Blvd,Metairie,LA,70002
143210,pBZQ1Ckxn_50xrFUSXOxNg,Sonic Drive-In,52,"Burgers, Food, Fast Food, Restaurants, Ice Cre...",2405 Easton Rd,WILLOW GROVE,PA,19090
146339,SS-UZH6n3FBUBCxx1SRoXA,Sonic Drive-In,50,"Restaurants, Hot Dogs, Ice Cream & Frozen Yogu...",1262 North Emerson Ave,Greenwood,IN,46143

In [43]:
#Dataframe merge ---- mAIN DATASET!!!
#Reviews X Business2df

dataset_df = pd.merge(df_review, df_business2, on="business_id")
dataset_df

,user_id,business_id,stars,useful,funny,cool,text,date,name,review_count,categories,address,city,state,postal_code
0,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0.0,0.0,0.0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11,Turning Point of North Wales,169,"Restaurants, Breakfast & Brunch, Food, Juice B...",1460 Bethlehem Pike,North Wales,PA,19454
1,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1.0,0.0,1.0,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03,Zaika,181,"Halal, Pakistani, Restaurants, Indian",2481 Grant Ave,Philadelphia,PA,19114
2,eUta8W_HdHMXPzLBBZhL1A,04UD14gamNjLY0IDYVhHJg,1.0,1.0,2.0,1.0,I am a long term frequent customer of this est...,2015-09-23 23:10:31,Dmitri's,273,"Mediterranean, Restaurants, Seafood, Greek",795 S 3rd St,Philadelphia,PA,19147
3,yfFzsLmaWF2d4Sr0UNbBgg,LHSTtnW3YHCeUkRDGyJOyw,5.0,2.0,0.0,0.0,Amazingly amazing wings and homemade bleu chee...,2015-08-07 02:29:16,Fries Rebellion,103,"Beer Bar, Bars, American (New), Gastropubs, Re...",1441 S West End Blvd,Quakertown,PA,18951
4,59MxRhNVhU9MYndMkz0wtw,gebiRewfieSdtt17PTW6Zg,3.0,0.0,0.0,0.0,Had a party of 6 here for hibachi. Our waitres...,2016-07-25 07:31:06,Hibachi Steak House & Sushi Bar,488,"Steakhouses, Sushi Bars, Restaurants, Japanese",502 State St,Santa Barbara,CA,93101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4890580,5hJR7ljJbhFgOaLi8iz5pQ,AXC__4yZrn-N3BT7-2bV_Q,NaN,NaN,NaN,NaN,"BOMB food. Super delicious, great outdoor spac...",2021-05-04 21:44:53,Biergarten,104,"Nightlife, Beer Gardens, Restaurants, Pizza, H...",11 Anacapa St,Santa Barbara,CA,93101
4890581,1uxtQAuJ2T5Xwa_wp7kUnA,OaGf0Dp56ARhQwIDT90w_g,NaN,NaN,NaN,NaN,Great food and service.,2021-10-30 11:54:36,Sus Hi Eatstation,50,"Restaurants, Sushi Bars",2309 E Fowler Ave,Tampa,FL,33612
4890582,v48Spe6WEpqehsF2xQADpg,hYnMeAO77RGyTtIzUSKYzQ,NaN,NaN,NaN,NaN,Love their Cubans!!,2021-11-05 13:18:56,The Strawberry Hut,118,"Restaurants, Sandwiches",1505 N Wheeler St,Plant City,FL,33563
4890583,ckqKGM2hl7I9Chp5IpAhkw,s2eyoTuJrcP7I_XyjdhUHQ,NaN,NaN,NaN,NaN,Great pizza great price,2021-11-20 16:11:44,Bros Pizzeria,172,"Pizza, Restaurants, Italian",547 S Fort Harrison Ave,Clearwater,FL,33756
4890584,4tF1CWdMxvvwpUIgGsDygA,_cb1Vg1NIWry8UA0jyuXnQ,NaN,NaN,NaN,NaN,Food is good value but a bit hot!,2021-12-07 22:30:00,Cheng Du,132,"Restaurants, Szechuan, Chinese",82 E Lancaster Ave,Paoli,PA,19301

In [ ]:
#checking if merged properly
df_check = dataset_df[dataset_df["name"] == "Zaika"]
df_check

In [ ]:
duplicates = df_check[df_check.duplicated(subset=['user_id'], keep=False)]
#print(duplicates)

#mqBWACmaHflW4eh_Ofp16Q
duplicates = duplicates[duplicates["user_id"].str.contains("mqBWACmaHflW4eh_Ofp16Q")]
print(duplicates[["user_id", "text"]])

Design choice - do A to C first then the other model

Explain why you chose the model - why and how did you apply this to the business Model

Try using smaller language model 7 million - one - reason - run through more data - more money

Try to use - instructor / response models - consistent and structuired op from llm

future examples and chain of thought

How to train - models that do sentiment already - HuggingFace - roberta - base models

use models like roberta to label it - ideal world you do human and AI annotation

Everywhere where confidence is over 85 - we assume it to be true if less we take a look at the sentiment and correct it.

ensemble models (LAST!!!!) - multiple models running at the same time - more agree more certain - 4 or more models running at the same time